### PR TITLE
Fewer backticks, and case insensitive UIDs

### PR DESCRIPTION
**Pull request by johnmckerrell**
Removed the backticks used for opening the door, made sure we can do a case insensitive search of uids.

### CODE REVIEW

**Comment by johnmckerrell** [comment]
I'm testing this on my desktop doorbot so will merge on Wednesday if approved (although I don't see an approval option here!)

**Comment by amcewen** [comment]
I'm not a huge fan of the brute force search for a user :-) but it's probably not going to be a huge issue for performance given how many users we've got.  I guess the simplest alternative would be to down- or upcase all the keys when the config first gets loaded, so the full pass through the array is only done once, at startup.

Otherwise LGTM.

**Comment by johnmckerrell** [comment]
Yeah, not ideal. I suppose an alternative is we document that it must be lower case! ;-)

**Comment by jackie1050** [comment]
That's what I was going to suggest - the app I use to get the tag ID shows uppercase letters so I just copied that in.
________________________________

**Comment by johnmckerrell** [comment]
Fixed the brute force aspect and actually also the fact that IDs that are all numbers would come through as such and that would break when comparing them to the strings we get from rcapp, so a second bug fixed!

Running this on my local test for another 24 hours or so before I'll push it through.

FWIW the backticks change did seem to work continuously for the week I was away recently but then kdeweb died!

**Pull request merged**
